server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

jwt:
  token:
    pubKeyPath:
    cookieName: gmall-token