server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.5:3306/guli_sms
    username: root
      password: Liu_123456
  redis:
        host: 10.211.55.5
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  global-config:
    db-config:
      id-type: auto